<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="4" total="12" passed="4" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-03T10:30:17 IST" name="Suite" finished-at="2025-02-03T10:31:46 IST" duration-ms="88539">
    <groups>
    </groups>
    <test started-at="2025-02-03T10:30:17 IST" name="Test" finished-at="2025-02-03T10:31:46 IST" duration-ms="88539">
      <class name="testCases.AddEmployeeTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.AddEmployeeTest@6f7923a5]" started-at="2025-02-03T10:30:18 IST" name="setup" finished-at="2025-02-03T10:30:25 IST" duration-ms="6975" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="addEmployee()[pri:0, instance:testCases.AddEmployeeTest@6f7923a5]" started-at="2025-02-03T10:30:25 IST" name="addEmployee" finished-at="2025-02-03T10:30:34 IST" duration-ms="9219" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.AddEmployeeTest.addEmployee(AddEmployeeTest.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployee -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.AddEmployeeTest@6f7923a5]" started-at="2025-02-03T10:30:34 IST" name="tearDown" finished-at="2025-02-03T10:30:34 IST" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.AddEmployeeTest@6f7923a5]" started-at="2025-02-03T10:30:34 IST" name="setup" finished-at="2025-02-03T10:30:38 IST" duration-ms="4260" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="addEmployee()[pri:0, instance:testCases.AddEmployeeTest@6f7923a5]" started-at="2025-02-03T10:30:38 IST" name="addEmployee" finished-at="2025-02-03T10:30:49 IST" duration-ms="10332" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployee -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.AddEmployeeTest@6f7923a5]" started-at="2025-02-03T10:30:49 IST" name="tearDown" finished-at="2025-02-03T10:30:49 IST" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.AddEmployeeTest -->
      <class name="testCases.DeleteEmployeeTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.DeleteEmployeeTest@36060e]" started-at="2025-02-03T10:31:36 IST" name="setup" finished-at="2025-02-03T10:31:40 IST" duration-ms="3869" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="deleteEmployee()[pri:0, instance:testCases.DeleteEmployeeTest@36060e]" started-at="2025-02-03T10:31:40 IST" name="deleteEmployee" finished-at="2025-02-03T10:31:46 IST" duration-ms="5934" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployee -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.DeleteEmployeeTest@36060e]" started-at="2025-02-03T10:31:46 IST" name="tearDown" finished-at="2025-02-03T10:31:46 IST" duration-ms="159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.DeleteEmployeeTest -->
      <class name="testCases.ExistEmployeeDetailsTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:30:49 IST" name="setup" finished-at="2025-02-03T10:30:53 IST" duration-ms="3797" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="existEmployeeDetails()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:30:53 IST" name="existEmployeeDetails" finished-at="2025-02-03T10:30:57 IST" duration-ms="4681" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.ExistEmployeeDetailsTest.existEmployeeDetails(ExistEmployeeDetailsTest.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- existEmployeeDetails -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:30:57 IST" name="tearDown" finished-at="2025-02-03T10:30:57 IST" duration-ms="161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:30:57 IST" name="setup" finished-at="2025-02-03T10:31:02 IST" duration-ms="4245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="existEmployeeDetails()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:31:02 IST" name="existEmployeeDetails" finished-at="2025-02-03T10:31:07 IST" duration-ms="4942" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.ExistEmployeeDetailsTest.existEmployeeDetails(ExistEmployeeDetailsTest.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- existEmployeeDetails -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:31:07 IST" name="tearDown" finished-at="2025-02-03T10:31:07 IST" duration-ms="189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:31:07 IST" name="setup" finished-at="2025-02-03T10:31:11 IST" duration-ms="4283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="existEmployeeDetails()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:31:11 IST" name="existEmployeeDetails" finished-at="2025-02-03T10:31:16 IST" duration-ms="4738" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.ExistEmployeeDetailsTest.existEmployeeDetails(ExistEmployeeDetailsTest.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- existEmployeeDetails -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:31:16 IST" name="tearDown" finished-at="2025-02-03T10:31:16 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:31:16 IST" name="setup" finished-at="2025-02-03T10:31:20 IST" duration-ms="4306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="existEmployeeDetails()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:31:20 IST" name="existEmployeeDetails" finished-at="2025-02-03T10:31:26 IST" duration-ms="5969" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- existEmployeeDetails -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.ExistEmployeeDetailsTest@1583741e]" started-at="2025-02-03T10:31:26 IST" name="tearDown" finished-at="2025-02-03T10:31:26 IST" duration-ms="170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.ExistEmployeeDetailsTest -->
      <class name="testCases.NotExistEmployeeDetailsTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.NotExistEmployeeDetailsTest@5b367418]" started-at="2025-02-03T10:31:26 IST" name="setup" finished-at="2025-02-03T10:31:30 IST" duration-ms="3869" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="notExistEmployeeDetails()[pri:0, instance:testCases.NotExistEmployeeDetailsTest@5b367418]" started-at="2025-02-03T10:31:30 IST" name="notExistEmployeeDetails" finished-at="2025-02-03T10:31:36 IST" duration-ms="5577" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- notExistEmployeeDetails -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.NotExistEmployeeDetailsTest@5b367418]" started-at="2025-02-03T10:31:36 IST" name="tearDown" finished-at="2025-02-03T10:31:36 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.NotExistEmployeeDetailsTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
